language: node_js

node_js:
  - '4'
  - '6'

before_script:
  - npm install -g gulp

script: gulp lint_and_test

after_success:
  - ./node_modules/.bin/istanbul cover test/**/*_test.js
  - ./node_modules/.bin/mocha test/**/*_test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
